import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  useEffect(() => {
    document.documentElement.lang = language;
    if (language === 'hi') {
      document.body.classList.add('lang-hi');
    } else {
      document.body.classList.remove('lang-hi');
    }
  }, [language]);

  const t = (key) => {
    const translations = {
      en: {
        open_invitation: "Open Invitation",
        hero_tagline: "Two souls, one heart.",
        save_the_date: "Save the Date",
        our_story: "Our Love Story",
        events: "Wedding Events",
        family: "Our Families",
        rsvp: "RSVP",
        venue: "Venue & Travel",
        gallery: "Gallery",
        boarding_pass: "Boarding Pass",
        wishes: "Wishes",
        see_you: "See You At The Wedding",
        groom: "Satyam",
        bride: "Shivangi",
        groom_full: "Satyam",
        bride_full: "Shivangi",
        couple_names: "Shivangi & Satyam",
        days: "Days",
        hours: "Hours",
        minutes: "Minutes",
        seconds: "Seconds",
        date_full: "1st July, 2026",
        
        // Invitation Card
        tap_open: "TAP TO OPEN",
        invitation_shloka: "॥ श्री गणेशाय नमः ॥\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
        together_families: "TOGETHER WITH THEIR FAMILIES",
        joyfully_invite: "Joyfully invite you to share in their happiness as they unite in marriage.",
        date_time: "WEDNESDAY, JULY 1, 2026\nAT FIVE O'CLOCK IN THE EVENING",
        palace_location: "Rosebay Resort, Raipur, Chhattisgarh",
        close_invitation: "CLOSE INVITATION",

        // Love Story
        story_1_title: "First Meet",
        story_1_date: "April 2022",
        story_1_desc: "A brief encounter at a cafe turned into a beautiful beginning.",
        story_2_title: "The Proposal",
        story_2_date: "December 2024",
        story_2_desc: "Under the starlit sky, a promise was made for a lifetime.",
        story_3_title: "Engagement",
        story_3_date: "January 2025",
        story_3_desc: "Officially joining our families with joy and traditions.",
        story_groom_title: "Satyam",
        story_groom_subtitle: "The Groom",
        story_bride_title: "Shivangi",
        story_bride_subtitle: "The Bride",
        story_wedding_title: "Shubh Vivah",
        story_wedding_date: "July 1, 2026",
        story_wedding_desc: "The day we become one forever.",
        story_continued: "To be continued...",

        // Events
        event_welcome: "Welcome Reception",
        event_carnival: "Vibrant Carnival",
        event_sangeet: "Sangeet Gala",
        event_bhaat: "Bhaat, Mayra & Gor",
        event_barat: "Nikashi & Barat",
        event_reception: "Grand Reception",
        event_varmala: "Sacred Varmala",
        event_phere: "Holy Phere",
        day_1_title: "Pre-Wedding Celebrations",
        day_2_title: "The Wedding Ceremonies",
        quote_timeline: "The celebrations begin! Join us in weaving memories that we will cherish for a lifetime.",
        dress_code: "Dress Code",
        venue_label: "Venue",
        click_details: "CLICK FOR DETAILS",

        date_june30: "June 30, 2026",
        date_july1: "July 1, 2026",

        time_9_30am: "9:30 AM",
        time_10am: "10:00 AM",
        time_8pm: "8:00 PM",
        time_5pm: "5:00 PM",
        time_9pm: "9:00 PM",
        time_phere: "Late Night (Auspicious Muhurat)",

        venue_welcome: "Palace Lobby / Main Entrance",
        venue_carnival: "Grand Palace Lawn & Gardens",
        venue_sangeet: "Grand Ballroom",
        venue_bhaat: "Inner Palace Courtyard",
        venue_barat: "Temple Gate to Main Lawn",
        venue_reception: "Grand Palace Lawn",
        venue_varmala: "Royal Wedding Stage",
        venue_phere: "Royal Mandap",

        dress_welcome: "Smart Casuals / Pastel Elegance",
        dress_carnival: "Vibrant & Floral Resort Wear",
        dress_sangeet: "Glamorous Indo-Western Couture",
        dress_bhaat: "Traditional Yellow / Pila",
        dress_barat: "Traditional Royals / Sherwanis & Safas",
        dress_reception: "Black Tie / Elegant Gowns",
        dress_varmala: "Royal Wedding Wear",
        dress_phere: "Sacred Traditional Wedding Couture",
        
        desc_welcome: "A warm traditional welcome to all our guests. Join us for morning tea and greetings as we kick off the beautiful celebrations!",
        desc_carnival: "Get ready for a high-energy festive Carnival! Packed with fun games, live food counters, vibrant photo booths, and beautiful memories.",
        desc_sangeet: "Dance, music, and endless joy! Our family members present choreographed routines, followed by an open dance floor with live DJ beats.",
        desc_bhaat: "A heartwarming traditional custom of love and maternal blessings. Bhaat and Mayra ceremonies bringing family closer together.",
        desc_barat: "The grand wedding procession! Join the groom on a musical dhol ride with enthusiastic dancing as we march towards the mandap.",
        desc_reception: "A formal grand gala to celebrate the newlywed couple. Join us for a beautiful dinner party, musical performances, and toasts.",
        desc_varmala: "The beautiful exchange of floral garlands under the fireworks sky, representing the union of our souls.",
        desc_phere: "Taking the sacred seven vows around the holy fire in the auspicious night muhurat to unite us for seven lifetimes.",
        
        // Gallery
        memories: "Memories",

        // Family
        relation_grandparents: "Grandparents",
        relation_parents: "Parents (Mummy-Papa)",
        relation_aunt_uncle: "Aunt & Uncle",
        relation_bua_fufa: "Bua & Fufa",
        bride_family_title: "Shivangi's Family",
        groom_family_title: "Satyam's Family",
        
        bride_gparents: "Shrimati Trimurti Devi & Late Omprakash Madiniya ji",
        bride_parents: "Shrimati Prachi & Shri Bajrang Jindal ji",
        bride_couple_1: "Shrimati Kaushalya & Shri Ashok Jindal ji",
        bride_couple_2: "Shrimati Anuradha & Shri Subhash Jindal ji",
        bride_couple_3: "Shrimati Sunita & Shri Rajesh Jindal ji",
        
        groom_gparents: "Late Shrimati Sharbati Devi & Late Tarachand Agrawal ji",
        groom_parents: "Shrimati Kaushal & Shri Laxmi Narayan Agrawal ji",
        groom_couple_1: "Shrimati Savita & Shri Mahavir Agrawal ji",
        groom_couple_2: "Shrimati Pushpa & Shri Brijmohan Agrawal ji",
        groom_couple_3: "Shrimati Sunita & Shri Anand Agrawal ji",
        groom_couple_4: "Shrimati Sarita & Shri Ashok Agrawal ji",
        relation_awaiting: "Awaiting to Welcome",
        bride_awaiting: [
          "Sweety & Deepak Jindal",
          "Aasha & Ravi Jindal",
          "Ritu & Jitendra Jindal",
          "Usha & Pawan Agrawal",
          "Payal & Saurabh Agrawal",
          "Pooja & Shubham",
          "Neha & Vipin",
          "Khushbu & Pulkit",
          "Sakshi & Navodit",
          "Ekta & Ayush",
          "Saubhagya",
          "Vikash",
          "Gaurav"
        ],
        groom_awaiting: [
          "Riti & Dr. Pradeep Agrawal",
          "Preeti & Sandeep Agrawal",
          "Poorvi & Shubham Agrawal",
          "Seema & Ritesh",
          "Neetu & Ashok",
          "Mamta & Abhishek",
          "Preeti & Saurabh",
          "Priyanka & Ram",
          "Neetu & Ravi",
          "Pooja & Ritesh",
          "Ritu & Vinay",
          "Neha & Ankit",
          "Muskan & Aneesh",
          "Anushka & Siddharth",
          "Vikki",
          "Aman",
          "Yash"
        ],

        // RSVP
        rsvp_deadline: "KINDLY RESPOND BY JUNE 10, 2026",
        rsvp_thanks: "Thank You!",
        rsvp_received: "We have received your response.",
        form_name: "Full Name",
        form_guests: "No. of Guests",
        form_attendance: "Attendance",
        form_accept: "Joyfully Accepts",
        form_decline: "Regretfully Declines",
        form_food: "Food Preference",
        form_veg: "Vegetarian",
        form_nonveg: "Non-Vegetarian",
        form_vegan: "Vegan",
        form_message: "Message or Blessings for the couple...",
        form_submit: "SEND RSVP",

        // Venue
        venue_title: "Rosebay Resort",
        venue_address: "Raipur, Chhattisgarh, India",
        get_directions: "GET DIRECTIONS",
        travel: "Travel",
        travel_air: "By Air",
        nearest_airport: "Nearest Airport: Swami Vivekananda Airport, Raipur (RPR) (approx. 15km)",
        get_route_air: "Get Route from Airport",
        travel_train: "By Train",
        nearest_station: "Nearest Station: Raipur Junction Railway Station (RPR) (approx. 10km)",
        get_route_train: "Get Route from Station",
        accommodation: "Accommodation",
        acc_details: "Rooms have been reserved at our partner hotels.",
        emergency_contacts: "Emergency Contacts",

        // Boarding Pass
        bp_title: "Your Boarding Pass",
        bp_subtitle: "Enter your name to generate your personal boarding pass to our wedding.",
        bp_placeholder: "Enter your full name",
        bp_generate: "GENERATE",
        bp_passenger: "Passenger",
        bp_date_label: "Date",
        bp_date_val: "29 JUN 2026",
        bp_home: "HOME",
        bp_anywhere: "Anywhere",
        bp_dest: "RPR",
        bp_dest_full: "Raipur, India",
        bp_board_time: "Boarding Time",
        bp_seat: "Seat",
        bp_download: "DOWNLOAD",
        bp_processing: "PROCESSING...",
        bp_share: "SHARE",
        bp_create_another: "CREATE ANOTHER PASS",
        bp_share_title: "My Wedding Boarding Pass",
        bp_share_text: "I got my boarding pass for Shivangi & Satyam's wedding! Get yours here: https://as-wedding.vercel.app/ #ShivyamKaSangam",
        bp_error: "Sharing is not supported on this device/browser. Please download it instead.",
        bp_fail: "Failed to download the pass. Please try again.",

        // Wishes Wall
        wishes_title: "Wishes Wall",
        wishes_subtitle: "Leave a message for the couple.",
        wishes_add: "Add Your Blessing",
        wishes_name: "Your Name",
        wishes_msg: "Your Message...",
        wishes_post: "POST WISH",
        time_just_now: "Just now",
        time_2_days: "2 days ago",
        time_1_week: "1 week ago",
        time_2_weeks: "2 weeks ago",
        wish_name_1: "Rahul & Sneha",
        wish_msg_1: "Wishing you a lifetime of love and happiness. Can't wait to celebrate!",
        wish_name_2: "Ananya",
        wish_msg_2: "So happy for you both! The perfect couple.",
        wish_name_3: "Karan",
        wish_msg_3: "Congratulations Shivangi and Satyam! Let the celebrations begin. #ShivyamKaSangam",

        // Final
        final_msg: "\"We can't wait to celebrate the beginning of our new life with all our loved ones.\""
      },
      hi: {
        open_invitation: "निमंत्रण खोलें",
        hero_tagline: "दो आत्माएं, एक दिल।",
        save_the_date: "तारीख याद रखें",
        our_story: "हमारी कहानी",
        events: "विवाह समारोह",
        family: "हमारे परिवार",
        rsvp: "आमंत्रण (RSVP)",
        venue: "स्थल और यात्रा",
        gallery: "गैलरी",
        boarding_pass: "बोर्डिंग पास",
        wishes: "शुभकामनाएँ",
        see_you: "शादी में मिलते हैं",
        groom: "सत्यम",
        bride: "शिवांगी",
        groom_full: "सत्यम",
        bride_full: "शिवांगी",
        couple_names: "शिवांगी और सत्यम",
        days: "दिन",
        hours: "घंटे",
        minutes: "मिनट",
        seconds: "सेकंड",
        date_full: "१ जुलाई, २०२६",
        
        // Invitation Card
        tap_open: "खोलने के लिए टैप करें",
        invitation_shloka: "॥ श्री गणेशाय नमः ॥\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
        together_families: "अपने परिवारों के साथ",
        joyfully_invite: "आपको उनके विवाह के पावन अवसर पर शामिल होने और खुशियां बांटने के लिए सहर्ष आमंत्रित करते हैं।",
        date_time: "बुधवार, १ जुलाई, २०२६\nशाम ५ बजे",
        palace_location: "रोज़बे रिज़ॉर्ट, रायपुर, छत्तीसगढ़",
        close_invitation: "निमंत्रण बंद करें",

        // Love Story
        story_1_title: "पहली मुलाकात",
        story_1_date: "अप्रैल २०२२",
        story_1_desc: "कैफे में एक छोटी सी मुलाकात एक खूबसूरत शुरुआत में बदल गई।",
        story_2_title: "प्रस्ताव",
        story_2_date: "दिसंबर २०२४",
        story_2_desc: "तारों से भरे आसमान के नीचे, जीवन भर का वादा किया गया।",
        story_3_title: "सगाई",
        story_3_date: "जनवरी २०२५",
        story_3_desc: "खुशी और परंपराओं के साथ आधिकारिक तौर पर हमारे परिवारों को जोड़ना।",
        story_groom_title: "सत्यम",
        story_groom_subtitle: "दूल्हा",
        story_bride_title: "शिवांगी",
        story_bride_subtitle: "दुल्हन",
        story_wedding_title: "शुभ विवाह",
        story_wedding_date: "१ जुलाई, २०२६",
        story_wedding_desc: "वह दिन जब हम हमेशा के लिए एक हो जाएंगे।",
        story_continued: "जारी रहेगा...",

        // Events
        event_welcome: "स्वागत समारोह (Welcome)",
        event_carnival: "कार्निवल उत्सव (Carnival)",
        event_sangeet: "संगीत संध्या (Sangeet)",
        event_bhaat: "भात, मायरा और गोर",
        event_barat: "निकासी और बारात",
        event_reception: "शाही रिसेप्शन (Reception)",
        event_varmala: "वरमाला समारोह",
        event_phere: "पवित्र फेरे",
        day_1_title: "प्री-वेडिंग समारोह",
        day_2_title: "मुख्य विवाह समारोह",
        quote_timeline: "उत्सव की मधुर शुरुआत! आइए इस पावन बेला में हमारे साथ मिलकर सुनहरी यादें संजोएं।",
        dress_code: "ड्रेस कोड",
        venue_label: "स्थल",
        click_details: "विवरण के लिए क्लिक करें",

        date_june30: "३० जून २०२६",
        date_july1: "१ जुलाई २०२६",

        time_9_30am: "सुबह ९:३0 बजे",
        time_10am: "सुबह १०:०० बजे",
        time_8pm: "रात ८:०० बजे",
        time_5pm: "शाम ५:०० बजे",
        time_9pm: "रात ९:०० बजे",
        time_phere: "देर रात (शुभ नक्षत्र मुहूर्त)",

        venue_welcome: "पैलेस लॉबी / प्रवेश द्वार",
        venue_carnival: "भव्य पैलेस गार्डन और लॉन",
        venue_sangeet: "ग्रैंड बॉलरूम",
        venue_bhaat: "पैलेस का भीतरी आंगन",
        venue_barat: "मंदिर द्वार से मुख्य लॉन तक",
        venue_reception: "भव्य पैलेस लॉन",
        venue_varmala: "शाही विवाह मंच",
        venue_phere: "शाही विवाह मंडप",

        dress_welcome: "स्मार्ट कैजुअल / पेस्टल रंग",
        dress_carnival: "वाइब्रेंट और फ्लोरल रिज़ॉर्ट वियर",
        dress_sangeet: "ग्लैमरस इंडो-वेस्टर्न",
        dress_bhaat: "पारंपरिक पीला वस्त्र (पिला)",
        dress_barat: "पारंपरिक राजसी वस्त्र / शेरवानी और साफा",
        dress_reception: "ब्लैक टाई / शाम के गाउन",
        dress_varmala: "शाही पारंपरिक विवाह परिधान",
        dress_phere: "पवित्र पारंपरिक विवाह परिधान",

        desc_welcome: "हमारे सभी मेहमानों का हार्दिक स्वागत। सुबह की चाय और मेल-मिलाप के साथ इस खूबसूरत उत्सव की शुरुआत में शामिल हों!",
        desc_carnival: "एक ऊर्जावान उत्सव कार्निवल के लिए तैयार हो जाइए! मजेदार खेल, स्वादिष्ट व्यंजन, जीवंत फोटो बूथ और खूबसूरत यादों से भरा हुआ दिन.",
        desc_sangeet: "नृत्य, संगीत और अंतहीन खुशी! हमारे परिवार के सदस्य कोरियोग्राफ किए गए नृत्य प्रस्तुत करेंगे, जिसके बाद डीजे फ्लोर पर उत्सव होगा.",
        desc_bhaat: "मातृ स्नेह और आशीर्वाद की एक दिल छू लेने वाली पारंपरिक रस्म। परिवार को और करीब लाने वाले भात और मायरा समारोह.",
        desc_barat: "भव्य बारात का आगमन! ढोल की थाप पर उत्साह के साथ नाचते हुए दूल्हे के साथ मंडप की ओर प्रस्थान करें.",
        desc_reception: "नवविवाहित जोड़े के सम्मान में एक शानदार शाम। लजीज भोजन, सुमधुर संगीत और शुभकामनाओं के साथ जश्न में शामिल हों.",
        desc_varmala: "आतिशबाज़ी से सजे आसमान के नीचे वरमाला का आदान-प्रदान, जो हमारी आत्माओं के मिलन का प्रतीक है.",
        desc_phere: "सात जन्मों के अटूट बंधन में बंधने के लिए शुभ रात्रिकालीन मुहूर्त में पवित्र अग्नि के फेरे और सात प्रतिज्ञाएं.",
        
        // Gallery
        memories: "यादें",

        // Family
        relation_grandparents: "दादी - दादा",
        relation_parents: "मम्मी - पापा",
        relation_aunt_uncle: "चाची - चाचा",
        relation_bua_fufa: "बुआ - फूफा",
        bride_family_title: "शिवांगी का परिवार",
        groom_family_title: "सत्यम का परिवार",
        
        bride_gparents: "श्रीमती त्रिमूर्ति देवी एवं स्व. ओमप्रकाश मदीनिया जी",
        bride_parents: "श्रीमती प्राची एवं श्री बजरंग जिंदल जी",
        bride_couple_1: "श्रीमती कौशल्या एवं श्री अशोक जिंदल जी",
        bride_couple_2: "श्रीमती अनुराधा एवं श्री सुभाष जिंदल जी",
        bride_couple_3: "श्रीमती सुनीता एवं श्री राजेश जिंदल जी",
        
        groom_gparents: "स्व. श्रीमती शर्बती देवी एवं स्व. ताराचंद अग्रवाल जी",
        groom_parents: "श्रीमती कौशल एवं श्री लक्ष्मी नारायण अग्रवाल जी",
        groom_couple_1: "श्रीमती सविता एवं श्री महावीर अग्रवाल जी",
        groom_couple_2: "श्रीमती पुष्पा एवं श्री बृजमोहन अग्रवाल जी",
        groom_couple_3: "श्रीमती सुनीता एवं श्री आनंद अग्रवाल जी",
        groom_couple_4: "श्रीमती सरिता एवं श्री अशोक अग्रवाल जी",
        relation_awaiting: "स्वागताकांक्षी",
        bride_awaiting: [
          "स्वीटी एवं दीपक जिंदल",
          "आशा एवं रवि जिंदल",
          "रितु एवं जितेन्द्र जिंदल",
          "ऊषा एवं पवन अग्रवाल",
          "पायल एवं सौरभ अग्रवाल",
          "पूजा एवं शुभम",
          "नेहा एवं विपिन",
          "खुशबू एवं पुलकित",
          "साक्षी एवं नवोदित",
          "एकता एवं आयुष",
          "सौभाग्य",
          "विकास",
          "गौरव"
        ],
        groom_awaiting: [
          "रीति एवं डॉ. प्रदीप अग्रवाल",
          "प्रीति एवं संदीप अग्रवाल",
          "पूर्वी एवं शुभम अग्रवाल",
          "सीमा एवं रितेश",
          "नीतू एवं अशोक",
          "ममता एवं अभिषेक",
          "प्रीति एवं सौरभ",
          "प्रियंका एवं राम",
          "नीतू एवं रवि",
          "पूजा एवं रितेश",
          "रितु एवं विनय",
          "नेहा एवं अंकित",
          "मुस्कान एवं अनीश",
          "अनुष्का एवं सिद्धार्थ",
          "विक्की",
          "अमन",
          "यश"
        ],

        // RSVP
        rsvp_deadline: "कृपया १ जून २०२६ तक उत्तर दें",
        rsvp_thanks: "धन्यवाद!",
        rsvp_received: "हमें आपका उत्तर मिल गया है।",
        form_name: "पूरा नाम",
        form_guests: "मेहमानों की संख्या",
        form_attendance: "उपस्थिति",
        form_accept: "खुशी से स्वीकार",
        form_decline: "खेद सहित अस्वीकार",
        form_food: "भोजन प्राथमिकता",
        form_veg: "शाकाहारी",
        form_nonveg: "मांसाहारी",
        form_vegan: "वीगन",
        form_message: "जोड़े के लिए संदेश या आशीर्वाद...",
        form_submit: "RSVP भेजें",

        // Venue
        venue_title: "रोज़बे रिज़ॉर्ट",
        venue_address: "रायपुर, छत्तीसगढ़, भारत",
        get_directions: "रास्ता देखें",
        travel: "यात्रा",
        travel_air: "हवाई मार्ग द्वारा",
        nearest_airport: "निकटतम हवाई अड्डा: स्वामी विवेकानंद हवाई अड्डा, रायपुर (RPR) (लगभग १५ किमी)",
        get_route_air: "हवाई अड्डे से रास्ता देखें",
        travel_train: "ट्रेन द्वारा",
        nearest_station: "निकटतम स्टेशन: रायपुर जंक्शन रेलवे स्टेशन (RPR) (लगभग १० किमी)",
        get_route_train: "स्टेशन से रास्ता देखें",
        accommodation: "आवास",
        acc_details: "हमारे पार्टनर होटलों में कमरे बुक किए गए हैं।",
        emergency_contacts: "आपातकालीन संपर्क / सहायता डेस्क",

        // Boarding Pass
        bp_title: "आपका बोर्डिंग पास",
        bp_subtitle: "हमारी शादी का व्यक्तिगत बोर्डिंग पास बनाने के लिए अपना नाम दर्ज करें।",
        bp_placeholder: "अपना पूरा नाम दर्ज करें",
        bp_generate: "जेनरेट करें",
        bp_passenger: "यात्री",
        bp_date_label: "तारीख",
        bp_date_val: "२९ जून २०२६",
        bp_home: "घर",
        bp_anywhere: "कहीं से भी",
        bp_dest: "रायपुर",
        bp_dest_full: "रायपुर, भारत",
        bp_board_time: "बोर्डिंग समय",
        bp_seat: "सीट",
        bp_download: "डाउनलोड",
        bp_processing: "प्रक्रिया हो रही है...",
        bp_share: "शेयर करें",
        bp_create_another: "नया पास बनाएं",
        bp_share_title: "मेरा वेडिंग बोर्डिंग पास",
        bp_share_text: "मुझे शिवांगी और सत्यम की शादी का बोर्डिंग पास मिल गया है! अपना यहाँ प्राप्त करें: https://as-wedding.vercel.app/ #ShivyamKaSangam",
        bp_error: "इस डिवाइस/ब्राउज़र पर शेयरिंग समर्थित नहीं है। कृपया इसे डाउनलोड करें।",
        bp_fail: "पास डाउनलोड करने में विफल। कृपया पुनः प्रयास करें।",

        // Wishes Wall
        wishes_title: "शुभकामनाएँ",
        wishes_subtitle: "जोड़े के लिए एक संदेश छोड़ें।",
        wishes_add: "अपना आशीर्वाद जोड़ें",
        wishes_name: "आपका नाम",
        wishes_msg: "आपका संदेश...",
        wishes_post: "शुभकामना भेजें",
        time_just_now: "अभी-अभी",
        time_2_days: "२ दिन पहले",
        time_1_week: "१ सप्ताह पहले",
        time_2_weeks: "२ सप्ताह पहले",
        wish_name_1: "राहुल और स्नेहा",
        wish_msg_1: "आपको जीवन भर प्यार और खुशी की शुभकामनाएं। जश्न मनाने का बेसब्री से इंतजार है!",
        wish_name_2: "अनन्या",
        wish_msg_2: "आप दोनों के लिए बहुत खुश हूँ! एकदम सही जोड़ी।",
        wish_name_3: "करन",
        wish_msg_3: "शिवांगी और सत्यम को बधाई! चलिए जश्न शुरू करते हैं। #ShivyamKaSangam",

        // Final
        final_msg: "\"हम अपने सभी प्रियजनों के साथ अपने नए जीवन की शुरुआत का जश्न मनाने के लिए उत्सुक हैं।\""
      }
    };
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
