import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  useEffect(() => {
    document.documentElement.lang = language;
    if (language === 'hi') {
      document.body.classList.add('lang-hi');
    } else {
      document.body.classList.remove('lang-hi');
    }
  }, [language]);

  const t = (key) => {
    const translations = {
      en: {
        open_invitation: "Open Invitation",
        hero_tagline: "Two souls, one heart.",
        save_the_date: "Save the Date",
        our_story: "Our Love Story",
        events: "Wedding Events",
        family: "Our Families",
        rsvp: "RSVP",
        venue: "Venue & Travel",
        gallery: "Gallery",
        boarding_pass: "Boarding Pass",
        wishes: "Wishes",
        see_you: "See You At The Wedding",
        groom: "Satyam",
        bride: "Shivangi",
        groom_full: "Satyam",
        bride_full: "Shivangi",
        couple_names: "Satyam & Shivangi",
        days: "Days",
        hours: "Hours",
        minutes: "Minutes",
        seconds: "Seconds",
        date_full: "Wednesday, 1st July, 2026",
        keep_scrolling: "Keep Scrolling",

        // Invitation Card
        tap_open: "TAP TO OPEN",
        invitation_shloka: "॥ श्री गणेशाय नमः ॥\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
        together_families: "TOGETHER WITH THEIR FAMILIES",
        joyfully_invite: "Joyfully invite you to share in their happiness as they unite in marriage.",
        date_time: "WEDNESDAY, JULY 1, 2026",
        palace_location: "Rosebey Resort, Raipur, Chhattisgarh",
        scroll_down: "SCROLL DOWN",

        // Love Story
        story_1_title: "First Meet",
        story_1_date: "1st April, 2026",
        story_1_desc: "A chance encounter that sparked something truly magical between two souls.",
        story_2_title: "The Proposal",
        story_2_date: "4th April, 2026",
        story_2_desc: "A heartfelt telephonic proposal — and she said yes without a second thought.",
        story_3_title: "Surprise Long Drive",
        story_3_date: "17th April, 2026",
        story_3_desc: "An unplanned long drive under open skies — every mile felt like a dream.",
        story_4_title: "The Engagement",
        story_4_date: "23rd April, 2026",
        story_4_desc: "Officially joining our families with joy, love, and beautiful traditions.",
        story_5_title: "Magical Date Night",
        story_5_date: "25th April, 2026",
        story_5_desc: "An enchanting evening full of love, laughter, and unforgettable moments.",
        story_groom_title: "Satyam",
        story_groom_subtitle: "The Groom",
        story_bride_title: "Shivangi",
        story_bride_subtitle: "The Bride",
        story_wedding_title: "Shubh Vivaah",
        story_wedding_date: "July 1, 2026",
        story_wedding_desc: "The day we become one forever.",
        story_continued: "To be continued...",

        // Events
        event_welcome: "Welcome",
        event_carnival: "Vibrant Carnival",
        event_sangeet: "Sangeet Gala",
        event_bhaat: "Mayara & Gor",
        event_barat: "Nikasi & Barat",
        event_reception: "Grand Reception",
        event_varmala: "Sacred Varmala",
        event_phere: "Holy Phere",
        day_1_title: "Pre-Wedding Celebrations",
        day_2_title: "The Wedding Ceremonies",
        quote_timeline: "The celebrations begin! Join us in weaving memories that we will cherish for a lifetime.",
        dress_code: "Dress Code",
        venue_label: "Venue",
        click_details: "CLICK FOR DETAILS",

        date_june30: "June 30, 2026",
        date_july1: "July 1, 2026",

        time_9_30am: "9:30 AM",
        time_10am: "10:00 AM",
        time_8pm: "8:00 PM",
        time_5pm: "5:00 PM",
        time_9pm: "9:00 PM",
        time_phere: "Late Night (Auspicious Muhurat)",

        venue_welcome: "Palace Lobby / Main Entrance",
        venue_carnival: "Grand Palace Lawn & Gardens",
        venue_sangeet: "Grand Ballroom",
        venue_bhaat: "Inner Palace Courtyard",
        venue_barat: "Temple Gate to Main Lawn",
        venue_reception: "Grand Palace Lawn",
        venue_varmala: "Royal Wedding Stage",
        venue_phere: "Royal Mandap",

        dress_welcome: "Smart Casuals / Pastel Elegance",
        dress_carnival: "Vibrant & Floral Resort Wear",
        dress_sangeet: "Glamorous Indo-Western Couture",
        dress_bhaat: "Traditional Yellow / Pila",
        dress_barat: "Traditional Royals / Sherwanis & Safas",
        dress_reception: "Black Tie / Elegant Gowns",
        dress_varmala: "Royal Wedding Wear",
        dress_phere: "Sacred Traditional Wedding Couture",

        desc_welcome: "A warm traditional welcome to all our guests. Join us for morning tea and greetings as we kick off the beautiful celebrations!",
        desc_carnival: "Get ready for a high-energy festive Carnival! Packed with fun games, live food counters, vibrant photo booths, and beautiful memories.",
        desc_sangeet: "Dance, music, and endless joy! Our family members present choreographed routines, followed by an open dance floor with live DJ beats.",
        desc_bhaat: "A heartwarming traditional custom of love and maternal blessings. Bhaat and Mayra ceremonies bringing family closer together.",
        desc_barat: "The grand wedding procession! Join the groom on a musical dhol ride with enthusiastic dancing as we march towards the mandap.",
        desc_reception: "A formal grand gala to celebrate the newlywed couple. Join us for a beautiful dinner party, musical performances, and toasts.",
        desc_varmala: "The beautiful exchange of floral garlands under the fireworks sky, representing the union of our souls.",
        desc_phere: "Taking the sacred seven vows around the holy fire in the auspicious night muhurat to unite us for seven lifetimes.",

        // Gallery
        memories: "Memories",

        // Family
        relation_grandparents: "Grandparents",
        relation_parents: "Parents (Mummy-Papa)",
        relation_aunt_uncle: "Aunt & Uncle",
        relation_taiji_tauji: "Aunt & Uncle",
        relation_bua_fufa: "Aunt & Uncle",
        bride_family_title: "Shivangi's Family",
        groom_family_title: "Satyam's Family",

        bride_gparents: "Shrimati Murti Devi & Late Shri Omprakash Madiniya",
        bride_parents: "Shrimati Prachi & Late Shri Bajrang Jindal",
        bride_couple_1: "Shrimati Kaushalya & Shri Ashok Jindal",
        bride_couple_2: "Shrimati Anuradha & Shri Subhash Jindal",
        bride_couple_3: "Shrimati Sunita & Shri Rajesh Jindal",

        groom_gparents: "Late Shrimati Sharbati Devi & Late Shri Tarachand Agrawal",
        groom_parents: "Shrimati Kaushal & Shri Laxmi Narayan Agrawal",
        groom_couple_1: "Shrimati Savita & Mahabir",
        groom_couple_2: "Shrimati Pushpa & Shri Brijmohan Agrawal",
        groom_couple_3: "Shrimati Sunita & Shri Anand Agrawal",
        groom_couple_4: "Shrimati Sarita & Shri Ashok Agrawal",
        relation_awaiting: "Awaiting to Welcome",
        bride_awaiting: [
          "Usha & Pawan Agrawal",
          "Sweety & Deepak Jindal",
          "Aasha & Ravi Jindal",
          "Ritu & Jitendra Jindal",
          "Aashi & Prince Jindal",
          "Payal & Saurabh Agrawal",
          "Pooja & Shubham ji",
          "Neha & Vipin ji",
          "Khushbu & Pulkit ji",
          "Sakshi & Navodit ji",
          "Ekta & Ayush ji",
          "Muskan",
          "Saubhagya",
          "Vikash",
          "Gaurav"
        ],
        groom_awaiting: [
          "Reeti & Dr. Pradeep Agrawal",
          "Preeti & Sandeep Agrawal",
          "Purvi & Shubham Agrawal",
          "Seema & Ritesh Ji",
          "Neetu & Ashok Ji",
          "Mamta & Abhishek Ji",
          "Preeti & Saurabh Ji",
          "Priyanka & Ram Ji",
          "Neetu & Ravi Ji",
          "Pooja & Ritesh Ji",
          "Ritu & Vinay Ji",
          "Neha & Ankit Ji",
          "Muskan & Anish Ji",
          "Anushka & Siddharth Ji",
          "Vickey",
          "Aman",
          "Yash"
        ],

        // RSVP
        rsvp_deadline: "KINDLY RESPOND BY JUNE 10, 2026",
        rsvp_thanks: "Thank You!",
        rsvp_received: "We have received your response.",
        form_name: "Full Name",
        form_guests: "No. of Guests",
        form_attendance: "Attendance",
        form_accept: "Joyfully Accepts",
        form_decline: "Regretfully Declines",
        form_food: "Food Preference",
        form_veg: "Vegetarian",
        form_nonveg: "Non-Vegetarian",
        form_vegan: "Vegan",
        form_message: "Message or Blessings for the couple...",
        form_submit: "SEND RSVP",

        // Venue
        venue_title: "Rosebey Resort",
        venue_address: "Raipur, Chhattisgarh, India",
        get_directions: "GET DIRECTIONS",
        travel: "Travel",
        travel_air: "By Air",
        nearest_airport: "Nearest Airport: Swami Vivekananda Airport, Raipur (RPR) (approx. 15km)",
        get_route_air: "Get Route from Airport",
        travel_train: "By Train",
        nearest_station: "Nearest Station: Raipur Junction Railway Station (RPR) (approx. 10km)",
        get_route_train: "Get Route from Station",
        accommodation: "Accommodation",
        acc_details: "Rooms have been reserved at our partner hotels.",
        emergency_contacts: "Emergency Contacts",

        // Boarding Pass
        bp_title: "Your Boarding Pass",
        bp_subtitle: "Enter your name to generate your personal boarding pass to our wedding.",
        bp_placeholder: "Enter your full name",
        bp_generate: "GENERATE",
        bp_passenger: "Passenger",
        bp_date_label: "Date",
        bp_date_val: "29 JUN 2026",
        bp_home: "HOME",
        bp_anywhere: "Anywhere",
        bp_dest: "RPR",
        bp_dest_full: "Raipur, India",
        bp_board_time: "Boarding Time",
        bp_seat: "Seat",
        bp_download: "DOWNLOAD",
        bp_processing: "PROCESSING...",
        bp_share: "SHARE",
        bp_create_another: "CREATE ANOTHER PASS",
        bp_share_title: "My Wedding Boarding Pass",
        bp_share_text: "I got my boarding pass for Satyam & Shivangi's wedding! Get yours here: https://as-wedding.vercel.app/ #ShivyamKaSangam",
        bp_error: "Sharing is not supported on this device/browser. Please download it instead.",
        bp_fail: "Failed to download the pass. Please try again.",

        // Wishes Wall
        wishes_title: "Wishes Wall",
        wishes_subtitle: "Leave a message for the couple.",
        wishes_add: "Add Your Blessing",
        wishes_name: "Your Name",
        wishes_msg: "Your Message...",
        wishes_post: "POST WISH",
        time_just_now: "Just now",
        time_2_days: "2 days ago",
        time_1_week: "1 week ago",
        time_2_weeks: "2 weeks ago",
        wish_name_1: "Rahul & Sneha",
        wish_msg_1: "Wishing you a lifetime of love and happiness. Can't wait to celebrate!",
        wish_name_2: "Ananya",
        wish_msg_2: "So happy for you both! The perfect couple.",
        wish_name_3: "Karan",
        wish_msg_3: "Congratulations Satyam and Shivangi! Let the celebrations begin. #ShivyamKaSangam",

        // Final
        final_msg: "\"We can't wait to celebrate the beginning of our new life with all our loved ones.\"",
      },
      hi: {
        open_invitation: "निमंत्रण खोलें",
        hero_tagline: "दो आत्माएं, एक दिल।",
        save_the_date: "तारीख याद रखें",
        our_story: "हमारी कहानी",
        events: "विवाह समारोह",
        family: "हमारे परिवार",
        rsvp: "आमंत्रण (RSVP)",
        venue: "स्थल और यात्रा",
        gallery: "गैलरी",
        boarding_pass: "बोर्डिंग पास",
        wishes: "शुभकामनाएँ",
        see_you: "शादी में मिलते हैं",
        groom: "सत्यम",
        bride: "शिवांगी",
        groom_full: "सत्यम",
        bride_full: "शिवांगी",
        couple_names: "सत्यम और शिवांगी",
        days: "दिन",
        hours: "घंटे",
        minutes: "मिनट",
        seconds: "सेकंड",
        date_full: "बुधवार, १ जुलाई, २०२६",
        keep_scrolling: "नीचे स्क्रॉल करें",

        // Invitation Card
        tap_open: "खोलने के लिए टैप करें",
        invitation_shloka: "॥ श्री गणेशाय नमः ॥\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
        together_families: "अपने परिवारों के साथ",
        joyfully_invite: "आपको उनके विवाह के पावन अवसर पर शामिल होने और खुशियां बांटने के लिए सहर्ष आमंत्रित करते हैं।",
        date_time: "बुधवार, १ जुलाई, २०२६\nशाम ५ बजे से",
        palace_location: "रोज़बे रिज़ॉर्ट, रायपुर, छत्तीसगढ़",
        scroll_down: "नीचे स्क्रॉल करें",

        // Love Story
        story_1_title: "पहली मुलाकात",
        story_1_date: "१ अप्रैल, २०२६",
        story_1_desc: "एक अनोखी मुलाकात जिसने दो दिलों में जादू जगा दिया।",
        story_2_title: "प्रेम प्रस्ताव",
        story_2_date: "४ अप्रैल, २०२६",
        story_2_desc: "एक दिल को छू लेने वाला फ़ोन पर प्रस्ताव — और उसने हाँ कह दी।",
        story_3_title: "सरप्राइज़ लॉन्ग ड्राइव",
        story_3_date: "१७ अप्रैल, २०२६",
        story_3_desc: "खुले आसमान के नीचे एक अनोखी लॉन्ग ड्राइव जहाँ हर पल जादुई था।",
        story_4_title: "सगाई",
        story_4_date: "२३ अप्रैल, २०२६",
        story_4_desc: "खुशी, प्यार और परंपराओं के साथ आधिकारिक तौर पर दोनों परिवारों को जोड़ना।",
        story_5_title: "जादुई डेट नाइट",
        story_5_date: "२५ अप्रैल, २०२६",
        story_5_desc: "प्रेम, हँसी और अविस्मरणीय पलों से भरी एक मनमोहक शाम।",
        story_groom_title: "सत्यम",
        story_groom_subtitle: "दूल्हा",
        story_bride_title: "शिवांगी",
        story_bride_subtitle: "दुल्हन",
        story_wedding_title: "शुभ विवाह",
        story_wedding_date: "१ जुलाई, २०२६",
        story_wedding_desc: "वह दिन जब हम हमेशा के लिए एक हो जाएंगे।",
        story_continued: "जारी रहेगा...",

        // Events
        event_welcome: "स्वागत (Welcome)",
        event_carnival: "कार्निवल उत्सव (Carnival)",
        event_sangeet: "संगीत संध्या (Sangeet)",
        event_bhaat: "मायरा और गोर",
        event_barat: "निकासी और बारात",
        event_reception: "शाही रिसेप्शन (Reception)",
        event_varmala: "वरमाला समारोह",
        event_phere: "पवित्र फेरे",
        day_1_title: "प्री-वेडिंग समारोह",
        day_2_title: "मुख्य विवाह समारोह",
        quote_timeline: "उत्सव की मधुर शुरुआत! आइए इस पावन बेला में हमारे साथ मिलकर सुनहरी यादें संजोएं।",
        dress_code: "ड्रेस कोड",
        venue_label: "स्थल",
        click_details: "विवरण के लिए क्लिक करें",

        date_june30: "३० जून २०२६",
        date_july1: "१ जुलाई २०२६",

        time_9_30am: "सुबह ९:३0 बजे",
        time_10am: "सुबह १०:०० बजे",
        time_8pm: "रात ८:०० बजे",
        time_5pm: "शाम ५:०० बजे",
        time_9pm: "रात ९:०० बजे",
        time_phere: "देर रात (शुभ नक्षत्र मुहूर्त)",

        venue_welcome: "पैलेस लॉबी / प्रवेश द्वार",
        venue_carnival: "भव्य पैलेस गार्डन और लॉन",
        venue_sangeet: "ग्रैंड बॉलरूम",
        venue_bhaat: "पैलेस का भीतरी आंगन",
        venue_barat: "मंदिर द्वार से मुख्य लॉन तक",
        venue_reception: "भव्य पैलेस लॉन",
        venue_varmala: "शाही विवाह मंच",
        venue_phere: "शाही विवाह मंडप",

        dress_welcome: "स्मार्ट कैजुअल / पेस्टल रंग",
        dress_carnival: "वाइब्रेंट और फ्लोरल रिज़ॉर्ट वियर",
        dress_sangeet: "ग्लैमरस इंडो-वेस्टर्न",
        dress_bhaat: "पारंपरिक पीला वस्त्र (पिला)",
        dress_barat: "पारंपरिक राजसी वस्त्र / शेरवानी और साफा",
        dress_reception: "ब्लैक टाई / शाम के गाउन",
        dress_varmala: "शाही पारंपरिक विवाह परिधान",
        dress_phere: "पवित्र पारंपरिक विवाह परिधान",

        desc_welcome: "हमारे सभी मेहमानों का हार्दिक स्वागत। सुबह की चाय और मेल-मिलाप के साथ इस खूबसूरत उत्सव की शुरुआत में शामिल हों!",
        desc_carnival: "एक ऊर्जावान उत्सव कार्निवल के लिए तैयार हो जाइए! मजेदार खेल, स्वादिष्ट व्यंजन, जीवंत फोटो बूथ और खूबसूरत यादों से भरा हुआ दिन.",
        desc_sangeet: "नृत्य, संगीत और अंतहीन खुशी! हमारे परिवार के सदस्य कोरियोग्राफ किए गए नृत्य प्रस्तुत करेंगे, जिसके बाद डीजे फ्लोर पर उत्सव होगा.",
        desc_bhaat: "मातृ स्नेह और आशीर्वाद की एक दिल छू लेने वाली पारंपरिक रस्म। परिवार को और करीब लाने वाले भात और मायरा समारोह.",
        desc_barat: "भव्य बारात का आगमन! ढोल की थाप पर उत्साह के साथ नाचते हुए दूल्हे के साथ मंडप की ओर प्रस्थान करें.",
        desc_reception: "नवविवाहित जोड़े के सम्मान में एक शानदार शाम। लजीज भोजन, सुमधुर संगीत और शुभकामनाओं के साथ जश्न में शामिल हों.",
        desc_varmala: "आतिशबाज़ी से सजे आसमान के नीचे वरमाला का आदान-प्रदान, जो हमारी आत्माओं के मिलन का प्रतीक है.",
        desc_phere: "सात जन्मों के अटूट बंधन में बंधने के लिए शुभ रात्रिकालीन मुहूर्त में पवित्र अग्नि के फेरे और सात प्रतिज्ञाएं.",

        // Gallery
        memories: "यादें",

        // Family
        relation_grandparents: "दादी - दादा",
        relation_parents: "मम्मी - पापा",
        relation_aunt_uncle: "चाची - चाचा",
        relation_taiji_tauji: "ताईजी - ताऊजी",
        relation_bua_fufa: "बुआ - फूफा",
        bride_family_title: "शिवांगी का परिवार",
        groom_family_title: "सत्यम का परिवार",

        bride_gparents: "श्रीमती मूर्ति देवी एवं स्व. ओमप्रकाश मदीनिया",
        bride_parents: "श्रीमती प्राची एवं स्व. बजरंग जिंदल",
        bride_couple_1: "श्रीमती कौशल्या एवं श्री अशोक जिंदल",
        bride_couple_2: "श्रीमती अनुराधा एवं श्री सुभाष जिंदल",
        bride_couple_3: "श्रीमती सुनीता एवं श्री राजेश जिंदल",

        groom_gparents: "स्व. श्रीमती शर्बती देवी एवं स्व. ताराचंद अग्रवाल",
        groom_parents: "श्रीमती कौशल एवं श्री लक्ष्मी नारायण अग्रवाल",
        groom_couple_1: "श्रीमती सविता एवं महाबीर",
        groom_couple_2: "श्रीमती पुष्पा एवं श्री बृजमोहन अग्रवाल",
        groom_couple_3: "श्रीमती सुनीता एवं श्री आनंद अग्रवाल",
        groom_couple_4: "श्रीमती सरिता एवं श्री अशोक अग्रवाल",
        relation_awaiting: "स्वागताकांक्षी",
        bride_awaiting: [
          "ऊषा एवं पवन अग्रवाल",
          "स्वीटी एवं दीपक जिंदल",
          "आशा एवं रवि जिंदल",
          "रितु एवं जितेन्द्र जिंदल",
          "आशी एवं प्रिंस जिंदल",
          "पायल एवं सौरभ अग्रवाल",
          "पूजा एवं शुभम जी",
          "नेहा एवं विपिन जी",
          "खुशबू एवं पुलकित जी",
          "साक्षी एवं नवोदित जी",
          "एकता एवं आयुष जी",
          "मुस्कान",
          "सौभाग्य",
          "विकास",
          "गौरव"
        ],
        groom_awaiting: [
          "रीति एवं डॉ. प्रदीप अग्रवाल",
          "प्रीति एवं संदीप अग्रवाल",
          "पूर्वी एवं शुभम अग्रवाल",
          "सीमा एवं रितेश जी",
          "नीतू एवं अशोक जी",
          "ममता एवं अभिषेक जी",
          "प्रीति एवं सौरभ जी",
          "प्रियंका एवं राम जी",
          "नीतू एवं रवि जी",
          "पूजा एवं रितेश जी",
          "रितु एवं विनय जी",
          "नेहा एवं अंकित जी",
          "मुस्कान एवं अनिश जी",
          "अनुष्का एवं सिद्धार्थ जी",
          "विक्की",
          "अमन",
          "यश"
        ],

        // RSVP
        rsvp_deadline: "कृपया १ जून २०२६ तक उत्तर दें",
        rsvp_thanks: "धन्यवाद!",
        rsvp_received: "हमें आपका उत्तर मिल गया है।",
        form_name: "पूरा नाम",
        form_guests: "मेहमानों की संख्या",
        form_attendance: "उपस्थिति",
        form_accept: "खुशी से स्वीकार",
        form_decline: "खेद सहित अस्वीकार",
        form_food: "भोजन प्राथमिकता",
        form_veg: "शाकाहारी",
        form_nonveg: "मांसाहारी",
        form_vegan: "वीगन",
        form_message: "जोड़े के लिए संदेश या आशीर्वाद...",
        form_submit: "RSVP भेजें",

        // Venue
        venue_title: "रोज़बे रिज़ॉर्ट",
        venue_address: "रायपुर, छत्तीसगढ़, भारत",
        get_directions: "रास्ता देखें",
        travel: "यात्रा",
        travel_air: "हवाई मार्ग द्वारा",
        nearest_airport: "निकटतम हवाई अड्डा: स्वामी विवेकानंद हवाई अड्डा, रायपुर (RPR) (लगभग १५ किमी)",
        get_route_air: "हवाई अड्डे से रास्ता देखें",
        travel_train: "ट्रेन द्वारा",
        nearest_station: "निकटतम स्टेशन: रायपुर जंक्शन रेलवे स्टेशन (RPR) (लगभग १० किमी)",
        get_route_train: "स्टेशन से रास्ता देखें",
        accommodation: "आवास",
        acc_details: "हमारे पार्टनर होटलों में कमरे बुक किए गए हैं।",
        emergency_contacts: "आपातकालीन संपर्क / सहायता डेस्क",

        // Boarding Pass
        bp_title: "आपका बोर्डिंग पास",
        bp_subtitle: "हमारी शादी का व्यक्तिगत बोर्डिंग पास बनाने के लिए अपना नाम दर्ज करें।",
        bp_placeholder: "अपना पूरा नाम दर्ज करें",
        bp_generate: "जेनरेट करें",
        bp_passenger: "यात्री",
        bp_date_label: "तारीख",
        bp_date_val: "२९ जून २०२६",
        bp_home: "घर",
        bp_anywhere: "कहीं से भी",
        bp_dest: "रायपुर",
        bp_dest_full: "रायपुर, भारत",
        bp_board_time: "बोर्डिंग समय",
        bp_seat: "सीट",
        bp_download: "डाउनलोड",
        bp_processing: "प्रक्रिया हो रही है...",
        bp_share: "शेयर करें",
        bp_create_another: "नया पास बनाएं",
        bp_share_title: "मेरा वेडिंग बोर्डिंग पास",
        bp_share_text: "मुझे सत्यम और शिवांगी की शादी का बोर्डिंग पास मिल गया है! अपना यहाँ प्राप्त करें: https://as-wedding.vercel.app/ #ShivyamKaSangam",
        bp_error: "इस डिवाइस/ब्राउज़र पर शेयरिंग समर्थित नहीं है। कृपया इसे डाउनलोड करें।",
        bp_fail: "पास डाउनलोड करने में विफल। कृपया पुनः प्रयास करें।",

        // Wishes Wall
        wishes_title: "शुभकामनाएँ",
        wishes_subtitle: "जोड़े के लिए एक संदेश छोड़ें।",
        wishes_add: "अपना आशीर्वाद जोड़ें",
        wishes_name: "आपका नाम",
        wishes_msg: "आपका संदेश...",
        wishes_post: "शुभकामना भेजें",
        time_just_now: "अभी-अभी",
        time_2_days: "२ दिन पहले",
        time_1_week: "१ सप्ताह पहले",
        time_2_weeks: "२ सप्ताह पहले",
        wish_name_1: "राहुल और स्नेहा",
        wish_msg_1: "आपको जीवन भर प्यार और खुशी की शुभकामनाएं। जश्न मनाने का बेसब्री से इंतजार है!",
        wish_name_2: "अनन्या",
        wish_msg_2: "आप दोनों के लिए बहुत खुश हूँ! एकदम सही जोड़ी।",
        wish_name_3: "करन",
        wish_msg_3: "सत्यम और शिवांगी को बधाई! चलिए जश्न शुरू करते हैं। #ShivyamKaSangam",

        // Final
        final_msg: "\"हम अपने सभी प्रियजनों के साथ अपने नए जीवन की शुरुआत का जश्न मनाने के लिए उत्सुक हैं।\"",
        compliments: "सस्नेह निमंत्रक एवं दर्शनाभिलाषी:\nअग्रवाल, जिंदल एवं मदिनिया परिवार"
      }
    };
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
